### ISSUE TITLE
Bottom part of the selected dot cuts off

### ISSUE THREAD

**Issue by sagarvasnani** [afollestad/viewpagerdots#1]
**Library version:** 1.0.0
**Affected device(s):** OnePlus 5T with Android 9.0
**Bug:** The bottom part of the selected dot cuts off.

![Screenshot_20190531-183534](https://user-images.githubusercontent.com/23434917/58707987-19c29a00-83d4-11e9-9180-1deea588ad73.jpg)

![Screenshot_20190531-183548](https://user-images.githubusercontent.com/23434917/58707986-18916d00-83d4-11e9-9429-725fd0fb249d.jpg)

**XML file to reproduce:**
```
    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <androidx.viewpager.widget.ViewPager
            android:id="@+id/viewpager"
            android:layout_width="match_parent"
            android:layout_height="130dp" />

        <com.afollestad.viewpagerdots.DotsIndicator
            android:id="@+id/dots"
            android:layout_width="match_parent"
            android:layout_height="140dp"
            android:paddingBottom="20dp"
            app:dot_tint="@color/primary"
            app:dots_gravity="bottom|center"
            />

    </RelativeLayout>
```
I have tried playing with paddingBottom, height and marginBottom, but nothing helps.

**Comment by afollestad** [comment]
Padding bottom definitely won't do it, that will cut it off. I'm guessing it's because you're setting an explicit height - it should be `wrap_content`.

**Comment by sagarvasnani** [comment]
Setting the `dots_gravity` property to only `center` fixed the issue. The height had to be set to 8dp though.
